name: ci
on:
  push:
    branches: [main]
    paths: ['src/**', 'pom.xml']
  pull_request:
    paths: ['src/**', 'pom.xml']
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ./mvnw verify

