name: ci
on:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32
      - uses: ./.github/actions/local-build
      - uses: docker://alpine:3.20
      - name: risky-action [eco-design:pin=tag]
        uses: vendor/risky-action@v1
      - run: echo "no uses here"

